'''
Dictionary to map course names to their shorthand
'''

prereq_formats = {
    "Academic Resource Center": "ARC",
    "Actuarial Sciences": "BUAS",
    "Anthropology": "ANTH",
    "Arabic Language": "ARBC",
    "Art": "ART",
    "Art History": "AHS",
    "Asian Studies": "AST",
    "Basic Writing": "BSWT",
    "Biochemistry": "BCH",
    "Bioengineering": "BIEN",
    "Biology": "BIOL",
    "Biomedical Sciences": "BMSC",
    "Biophysics": "BPHY",
    "Black Study": "BLKS",
    "Botany/Plant Science": "BPSC",
    "Business": "BUS",
    "CHASS First Yr Experience Prog": "CHFY",
    "Cahuilla": "CAH",
    "Cell Biology and Neuroscience": "CBNS",
    "Cell, Molecular, and Develpmnt": "CMDB",
    "Chemical Engineering": "CHE",
    "Chemical and Environmental Eng": "CEE",
    "Chemistry": "CHEM",
    "Chinese": "CHN",
    "Classical Studies": "CLA",
    "Comparative Literature": "CPLT",
    "Computer Science": "CS",
    "Creative Writing": "CRWT",
    "Crwt Wrt &amp; Wrt for Perf Arts": "CWPA",
    "Dance": "DNCE",
    "Economics": "ECON",
    "Education": "EDUC",
    "Electrical Engineering": "EE",
    "Engineering": "ENGR",
    "English": "ENGL",
    "Entomology": "ENTM",
    "Environmental Engineering": "ENVE",
    "Environmental Sciences": "ENSC",
    "Environmental Toxicology": "ENTX",
    "Ethnic Studies": "ETST",
    "European Culture": "EUR",
    "Evoltn, Ecolgy, &amp; Orgnsml Bio": "EEOB",
    "Filipino": "FIL",
    "French": "FREN",
    "Gender and Sexuality Studies": "GSST",
    "Genetics": "GEN",
    "Geosciences": "GEO",
    "German": "GER",
    "Global Studies": "GBST",
    "Graduate Division": "GDIV",
    "Greek": "GRK",
    "History": "HIST",
    "History of Europe": "HISE",
    "History of the Americas": "HISA",
    "Honors": "HNPG",
    "Humanities, Arts and Soc Sci": "HASS",
    "Italian": "ITAL",
    "Japanese": "JPN",
    "Korean": "KOR",
    "Labor Studies": "LABR",
    "Latin": "LATN",
    "Latin American Studies": "LNST",
    "Law &amp; Society": "LWSO",
    "Lesbian, Gay, Bisexual Studies": "LGBS",
    "Liberal Studies Program": "LBST",
    "Linguistics": "LING",
    "Low Res-Crwt Wrt&amp;Wrt-Perf Arts": "CWLR",
    "Management": "MGT",
    "Materials Sci and Engineering": "MSE",
    "Mathematics": "MATH",
    "Mechanical Engineering": "ME",
    "Media and Cultural Studies": "MCS",
    "Microbiology": "MCBL",
    "Middle East and Islamic Stds": "MEIS",
    "Music": "MUS",
    "Natural &amp;Agricultural Sciences": "NASC",
    "Nematology": "NEM",
    "Neuroscience": "NRSC",
    "Peace and Conflict Studies": "PCST",
    "Philosophy": "PHIL",
    "Physics": "PHYS",
    "Plant Pathology": "PLPA",
    "Political Science": "POSC",
    "Psychology": "PSYC",
    "Public Health-Social Medicine": "PBHL",
    "Public Policy": "PBPL",
    "Religious Studies": "RLST",
    "Russian Studies": "RUSN",
    "School of Medicine": "MDCL",
    "Society, Envmnt, Health Equity": "SEHE",
    "Sociology": "SOC",
    "Southeast Asian Studies": "SEAS",
    "Spanish": "SPN",
    "Statistics": "STAT",
    "Theater, Film &amp; Digital Prod": "TFDP",
    "Urban Studies": "URST",
    "Vietnamese": "VNM",
}
